import dotenv from "dotenv";
import NodeCache from "node-cache";

dotenv.config();

let {
  APP_PUBLIC_KEY,
  APP_PRIVATE_KEY,
  ACCESS_TOKEN_TTL,
  REFRESH_TOKEN_TTL,
  MONGODB_URI,
  KYC_OTP_TTL,
  HASH_TTL,
  SUDO_TTL,
  SMTP_HOST,
  SMTP_USERNAME,
  SMTP_PASSWORD,
  SMTP_PORT,
  DEV_BASE_URL,
  CLIENT_BASE_URL,
  SENTRY_DSN,
  CRON_KEY,
  STREAM_KEY,
  ENV,
  IMAGE_UPLOAD_ENDPOINT,
  IMAGE_UPLOAD_KEY,
  GITHUB_CLIENT_ID,
  GITHUB_CLIENT_SECRET,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  BASE_URL,
  GITHUB_REDIRECT_URL,
  GOOGLE_REDIRECT_URL,
} = process.env;

ACCESS_TOKEN_TTL = ACCESS_TOKEN_TTL || "5m";
REFRESH_TOKEN_TTL = REFRESH_TOKEN_TTL || "1y";
KYC_OTP_TTL = KYC_OTP_TTL || "86400000"; // default: 24 hrs...(in milliseconds)
HASH_TTL = HASH_TTL || "86400000"; // default: 24 hrs...(in milliseconds)
SUDO_TTL = SUDO_TTL || "300000"; // default: 5 mins...(in milliseconds)
SMTP_HOST = SMTP_HOST || "";
SMTP_USERNAME = SMTP_USERNAME || "";
SMTP_PASSWORD = SMTP_PASSWORD || "";
SMTP_PORT = SMTP_PORT || "";
DEV_BASE_URL = DEV_BASE_URL || "http://localhost:5173";
CLIENT_BASE_URL = CLIENT_BASE_URL || "http://localhost:5173";
SENTRY_DSN = SENTRY_DSN || "";
ENV = ENV || "test";
IMAGE_UPLOAD_ENDPOINT = IMAGE_UPLOAD_ENDPOINT || "";
IMAGE_UPLOAD_KEY = IMAGE_UPLOAD_KEY || "";
STREAM_KEY = STREAM_KEY || "";
GITHUB_CLIENT_ID = GITHUB_CLIENT_ID || "";
GITHUB_CLIENT_SECRET = GITHUB_CLIENT_SECRET || "";
GOOGLE_CLIENT_ID = GOOGLE_CLIENT_ID || "";
GOOGLE_CLIENT_SECRET = GOOGLE_CLIENT_SECRET || "";
BASE_URL = BASE_URL || "";
GITHUB_REDIRECT_URL = BASE_URL + GITHUB_REDIRECT_URL;
GOOGLE_REDIRECT_URL = BASE_URL + GOOGLE_REDIRECT_URL;

const IS_PROD = ENV === "production";
const cache = new NodeCache({ stdTTL: 5 * 60 }); // 5 minutes

export default {
  APP_PRIVATE_KEY,
  APP_PUBLIC_KEY,
  ACCESS_TOKEN_TTL,
  REFRESH_TOKEN_TTL,
  MONGODB_URI,
  KYC_OTP_TTL,
  HASH_TTL,
  SUDO_TTL,
  SMTP_HOST,
  SMTP_PASSWORD,
  SMTP_USERNAME,
  SMTP_PORT,
  DEV_BASE_URL,
  CLIENT_BASE_URL,
  SENTRY_DSN,
  CRON_KEY,
  ENV,
  IS_PROD,
  IMAGE_UPLOAD_ENDPOINT,
  IMAGE_UPLOAD_KEY,
  STREAM_KEY,
  cache,
  GITHUB_CLIENT_ID,
  GITHUB_CLIENT_SECRET,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  BASE_URL,
  GITHUB_REDIRECT_URL,
  GOOGLE_REDIRECT_URL,
};
