import dotenv from "dotenv";

dotenv.config();

let {
  APP_PUBLIC_KEY,
  APP_PRIVATE_KEY,
  ACCESS_TOKEN_TTL,
  REFRESH_TOKEN_TTL,
  MONGODB_URI,
  KYC_OTP_TTL,
  HASH_TTL,
  SUDO_TTL,
  SMTP_HOST,
  SMTP_USERNAME,
  SMTP_PASSWORD,
  SMTP_PORT,
  DEV_BASE_URL,
  CLIENT_BASE_URL,
} = process.env;

ACCESS_TOKEN_TTL = ACCESS_TOKEN_TTL || "5m";
REFRESH_TOKEN_TTL = REFRESH_TOKEN_TTL || "1y";
KYC_OTP_TTL = KYC_OTP_TTL || "86400";
HASH_TTL = HASH_TTL || "86400";
SUDO_TTL = SUDO_TTL || "300";
SMTP_HOST = SMTP_HOST || "";
SMTP_USERNAME = SMTP_USERNAME || "";
SMTP_PASSWORD = SMTP_PASSWORD || "";
SMTP_PORT = SMTP_PORT || "";
DEV_BASE_URL = DEV_BASE_URL || "http://localhost:5173";
CLIENT_BASE_URL = CLIENT_BASE_URL || "http://localhost:5173";

export default {
  APP_PRIVATE_KEY,
  APP_PUBLIC_KEY,
  ACCESS_TOKEN_TTL,
  REFRESH_TOKEN_TTL,
  MONGODB_URI,
  KYC_OTP_TTL,
  HASH_TTL,
  SUDO_TTL,
  SMTP_HOST,
  SMTP_PASSWORD,
  SMTP_USERNAME,
  SMTP_PORT,
  DEV_BASE_URL,
  CLIENT_BASE_URL,
};
